"device" : "cuda"
"seed" : 7

"model_dir" : "./models/"
"model_name" : "best_model.pt"
"output_dir" : "./outputs/"

"batch_size" : 256
"dropout" : 0.2
"hidden_size" : 128
"emb_size" : 128
"n_layers" : 1
"n_head" : 8
"seq_len" : 256
"target_size" : 1
"n_epochs" : 5 
"lr" : 0.001

"cate_cols" :
- "userID"
- "assessmentItemID"
- "KnowledgeTag"
- "testCode"
- "testNum"
- "problemID"
- "Real_Solved"
- "itemID_high_freq"
- "testID_high_freq"
- "testCode_high_freq"
- "testNum_high_freq"
- "problemID_high_freq"
- "tag_high_freq"
- "is_correct_before1"
- "is_correct_before2"
- "is_correct_before3"
- "is_correct_before4"
- "is_correct_before5"

"cont_cols" :
- "problemID_Norm"
- "year"
- "month"
- "day"
- "hour"
- "dow"
- "weekday"
- "ElapsedTime"
- "ElapsedTime_Rolling2"
- "ElapsedTime_Rolling3"
- "ElapsedTime_Rolling4"
- "ElapsedTime_Rolling5"
- "user_ElaspedTime_avg"
- "item_ElaspedTime_avg"
- "testID_ElaspedTime_avg"
- "testCode_ElaspedTime_avg"
- "testNum_ElaspedTime_avg"
- "problemID_ElaspedTime_avg"
- "tag_ElaspedTime_avg"
- "Correct_User_ElapsedTime"
- "Wrong_User_ElapsedTime"
- "user_sum"
- "user_cnt"
- "user_acc"
- "user_itemID_sum"
- "user_itemID_cnt"
- "user_itemID_acc"
- "user_testID_sum"
- "user_testID_cnt"
- "user_testID_acc"
- "user_testCode_sum"
- "user_testCode_cnt"
- "user_testCode_acc"
- "user_testNum_sum"
- "user_testNum_cnt"
- "user_testNum_acc"
- "user_problemID_sum"
- "user_problemID_cnt"
- "user_problemID_acc"
- "user_tag_sum"
- "user_tag_cnt"
- "user_tag_acc"
- "itemID_sum"
- "itemID_cnt"
- "itemID_acc"
- "testID_sum"
- "testID_cnt"
- "testID_acc"
# - "testCode_sum" ################
# - "testCode_cnt" ################
# - "testCode_acc" ################
# - "testNum_sum" ################
# - "testNum_cnt" ################
# - "testNum_acc" ################
# - "problemID_sum" ################
# - "problemID_cnt" ################
# - "problemID_acc" ################
- "tag_sum"
- "tag_cnt"
- "tag_acc"
- "user_past_solved"
# - "relative_correct_rate" ################ 
# - "correct_rate_before1" ################
# - "relative_correct_rate_before1" ################
# - "correct_rate_before2" ################
# - "relative_correct_rate_before2" ################
# - "correct_rate_before3" ################
# - "relative_correct_rate_before3" ################
# - "correct_rate_before4" ################
# - "relative_correct_rate_before4" ################
# - "correct_rate_before5" ################
# - "relative_correct_rate_before5" ################
- "theta"
- "beta"
- "answerCode"
